### ISSUE TITLE
the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by ilogue** [codacy/codacy-coverage-reporter#122]
When running the coverage reporter version 6.0.0 on circle-ci as follows:
```
            . venv/bin/activate
            coverage xml -o coverage/coverage.xml
            java -jar ~/.cache/jars/codacy-coverage-reporter-6.0.0-assembly.jar report -l Python -r coverage/coverage.xml
            yarn report-coverage-codacy
            java -jar ~/.cache/jars/codacy-coverage-reporter-6.0.0-assembly.jar final
```

now fails with:

```
18:27:43.235 [main] INFO com.codacy.rules.ReportRules - Uploading coverage data...
Exception in thread "main" javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:408)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(AbstractDelegateHttpsURLConnection.java:100)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(AbstractDelegateHttpsURLConnection.java:80)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:723)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1602)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
	at scalaj.http.HttpRequest.scalaj$http$HttpRequest$$doConnection(Http.scala:367)
	at scalaj.http.HttpRequest.exec(Http.scala:343)
	at scalaj.http.HttpRequest.asString(Http.scala:491)
	at com.codacy.api.client.CodacyClient.post(CodacyClient.scala:72)
	at com.codacy.api.service.CoverageServices.sendReport(CoverageServices.scala:20)
	at com.codacy.rules.ReportRules$$anonfun$coverageWithTokenAndCommit$1$$anonfun$apply$2.apply(ReportRules.scala:62)
	at com.codacy.rules.ReportRules$$anonfun$coverageWithTokenAndCommit$1$$anonfun$apply$2.apply(ReportRules.scala:47)
	at cats.syntax.EitherOps$.flatMap$extension(either.scala:148)
	at com.codacy.rules.ReportRules$$anonfun$coverageWithTokenAndCommit$1.apply(ReportRules.scala:47)
	at com.codacy.rules.ReportRules$$anonfun$coverageWithTokenAndCommit$1.apply(ReportRules.scala:40)
	at cats.syntax.EitherOps$.flatMap$extension(either.scala:148)
	at com.codacy.rules.ReportRules.withCommitUUID(ReportRules.scala:124)
	at com.codacy.rules.ReportRules.coverageWithTokenAndCommit(ReportRules.scala:40)
	at com.codacy.rules.ReportRules.codacyCoverage(ReportRules.scala:30)
	at com.codacy.CodacyCoverageReporter$.run(CodacyCoverageReporter.scala:22)
	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:13)
	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:11)
	at caseapp.CommandAppWithPreCommand$$anonfun$main$1.apply(CommandAppWithPreCommand.scala:97)
	at caseapp.CommandAppWithPreCommand$$anonfun$main$1.apply(CommandAppWithPreCommand.scala:82)
	at scala.Option.foreach(Option.scala:257)
	at caseapp.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:82)
	at com.codacy.CodacyCoverageReporter.main(CodacyCoverageReporter.scala)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
	at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
	at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:308)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:176)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:188)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:626)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:461)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:361)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:448)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:425)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:178)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	... 30 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:86)
	... 46 more
Exited with code 1
```

gz#7669

**Comment by lolgab** [comment]
Public comment from Ivo in <a href='https://codacy.zendesk.com/agent/tickets/7669'>Zendesk ticket #7669</a>:<br><br>Hi Jasper,

Just to let you know that the bug you opened has been assigned to this quarter and so, we should have news on this soon.

You can follow any update on the bug itself.

In the meanwhile, please let me know if I can help with anything else.

Regards,
Ivo

Support Engineer at Codacy

**Comment by ljmf00** [comment]
Hey @ilogue ,

Could you please tell me your Java version?

**Comment by mrfyda** [comment]
Closing for now.
We were not able to replicate this behaviour.
