### ISSUE TITLE
CicleCi Orb not find codacy-coverage.json file

### ISSUE THREAD

**Issue by brunosmm** [codacy/codacy-coverage-reporter#217]
Hello,

I am trying to use the CircleCI orb in my pipeline and send the PHP clover report but I get an error:
```

2020-05-24 15:27:49.012Z  info [ReportRules] Parsing coverage data from: /home/circleci/repo/src/tests/results/coverage-report-clover/clover.xml ...  - (ReportRules.scala:48)
 
Exception in thread "main" java.io.FileNotFoundException: /home/circleci/repo/src/tests/results/coverage-report-clover/codacy-coverage.json (Permission denied)
 
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_io_FileNotFoundException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
 
	at java.io.FileOutputStream.open0(FileOutputStream.java)
 
	at java.io.FileOutputStream.open(FileOutputStream.java:298)
 
	at java.io.FileOutputStream.<init>(FileOutputStream.java:237)
 
	at java.io.FileOutputStream.<init>(FileOutputStream.java:187)
 
	at java.io.PrintWriter.<init>(PrintWriter.java:309)
 
	at com.codacy.api.helpers.FileHelper$.writeJsonToFile(FileHelper.scala:54)
 
	at com.codacy.rules.ReportRules.storeReport(ReportRules.scala:101)
 
	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$6(ReportRules.scala:52)
 
	at scala.util.Either.flatMap(Either.scala:341)
 
	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$4(ReportRules.scala:51)
 
	at scala.util.Either.flatMap(Either.scala:341)
 
	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$3(ReportRules.scala:50)
 
	at scala.collection.immutable.List.map(List.scala:286)
 
	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$2(ReportRules.scala:47)
 
	at scala.util.Either.flatMap(Either.scala:341)
 
	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$1(ReportRules.scala:40)
 
	at com.codacy.rules.ReportRules.$anonfun$withCommitUUID$4(ReportRules.scala:267)
 
	at com.codacy.rules.ReportRules.$anonfun$withCommitUUID$4$adapted(ReportRules.scala:267)
 
	at scala.util.Either.flatMap(Either.scala:341)
 
	at com.codacy.rules.ReportRules.withCommitUUID(ReportRules.scala:267)
 
	at com.codacy.rules.ReportRules.codacyCoverage(ReportRules.scala:35)
 
	at com.codacy.CodacyCoverageReporter$.$anonfun$sendReport$1(CodacyCoverageReporter.scala:43)
 
	at scala.util.Either.flatMap(Either.scala:341)
 
	at com.codacy.CodacyCoverageReporter$.sendReport(CodacyCoverageReporter.scala:34)
 
	at com.codacy.CodacyCoverageReporter$.run(CodacyCoverageReporter.scala:19)
 
	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:13)
 
	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:11)
 
	at caseapp.CommandAppWithPreCommand.$anonfun$main$1(CommandAppWithPreCommand.scala:97)
 
	at caseapp.CommandAppWithPreCommand.$anonfun$main$1$adapted(CommandAppWithPreCommand.scala:82)
 
	at scala.Option.foreach(Option.scala:407)
 
	at caseapp.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:82)
 
	at com.codacy.CodacyCoverageReporter.main(CodacyCoverageReporter.scala)
 

 
 --> Failed!
 
```
Seems to try to find a codacy-coverage.json but this file is not generated by phpUnit, just the clover.xml.
I didn't find any reference for this file here in the repo? I try to ssh in my pipeline but didn't find any file with Codacy name.

CircleCi Pipeline: https://app.circleci.com/pipelines/github/gsmainclusivetechlab/interop-sp-simulator/34/workflows/cacf568a-2329-4996-85fb-d73b6f6e920a/jobs/26

CircleCI Config file: https://github.com/gsmainclusivetechlab/interop-sp-simulator/blob/codacy-code-coverage/.circleci/config.yml

PHP test coverage to generate clover.xml:
`phpdbg -qrr vendor/bin/phpunit --coverage-html tests/results/coverage-report-html --coverage-clover tests/results/coverage-report-clover/clover.xml`
https://github.com/gsmainclusivetechlab/interop-sp-simulator/blob/codacy-code-coverage/src/Makefile

**Comment by franciscodua** [comment]
Hi @brunosmm 

The tool is not looking for that file but it's trying to create it. However, it doesn't have enough permissions to write it.

Checking your Makefile and Docker compose, it might be because of this mapping:
```
volumes:
  - ./src:/var/www/html
```
The tool probably doesn't have permission to write there.

**Note:** The file is the same information that is sent to Codacy and its main purpose is helping in troubleshooting.

Possible workarounds:
- Run the coverage reporter script in your machine and not in the Docker machine
  - Since you have the folder mapped, the report is also available in the machine and you don't require your build dependencies for the tool to run
- Give permissions for the tool to write in that folder

Let us know if this helped.

**Comment by brunosmm** [comment]
Hi @franciscodua,

Thanks for the support!
Indeed the makefile runs the report inside the docker, who writes the results in the repo/src/tests/results/coverage-report-clover/clover.xml.
This file is not inside the docker and the execution of codacy-coverage-reporter is execute in the machine define in CircleCI, not in the docker, at least from my understanding.
The run is using the codacy orb, so I don't have access to the commands executed inside the orb When you say give permission, should add a sudo to execute? Is that not suppose to be changed inside the orb?
The second alternative, how can I say to the Orb where to write the file?

**Comment by franciscodua** [comment]
> This file is not inside the docker and the execution of codacy-coverage-reporter is execute in the machine define in CircleCI, not in the docker, at least from my understanding.

You're right. But for some reason, it can't write in that directory.

> When you say give permission, should add a sudo to execute?

You should be able to follow this support [solution](https://support.circleci.com/hc/en-us/articles/360003649774-Permission-Denied-When-Creating-Directory-or-Writing-a-File).

> The second alternative, how can I say to the Orb where to write the file?

Currently you can't. This change is something we would have to do. But it seems a change that makes sense, to avoid these permission problems.

Meanwhile, if you try the first solution let us know if it worked.

**Comment by franciscodua** [comment]
@brunosmm we changed the tool to write to a temporary folder instead of writing to the code directory.

So you can probably rerun your workflow and test if it fixed the problem for you

**Comment by brunosmm** [comment]
Hi @franciscodua ,

Thanks for the fix, all working now!

Here the proof. 😄 
https://app.circleci.com/pipelines/github/gsmainclusivetechlab/interop-sp-simulator/34/workflows/bfaf8a39-2acd-4499-ac16-e7e3e002a179/jobs/29
