### ISSUE TITLE
SocketTimeout when uploading coverage from travis

### ISSUE THREAD

**Issue by grm** [codacy/codacy-coverage-reporter#226]
Hello, 

I am trying to integrate codacy coverage for my open source python project in travisci, but it does not seems to work (codecov is working fine) with a socket timeout issue.

The uploads fails from all my builds. I have setup the CODACY_PROJECT_TOKEN env variable as asked from documentation.

The result can be seen here : 
https://travis-ci.org/github/py-smart-gardena/py-smart-gardena/jobs/693000856#L308

Did I miss something ?

Thx,
Grm

**Comment by JoschuaGoetz** [comment]
I have the same issue running a bash script on teamcity. I checked all jar`s ranging from version 10.0.3 to 9.0.0. Got the same error on each try. 
Script 
```
curl -s https://coverage.codacy.com/get.sh | bash -s report -t %env.codacyToken% -l Python -r ./coverage.xml
```
Error
```
[11:29:22]	[Step 1/1] Send result to codacy
[11:29:22]	[Step 1/1]      ______          __
[11:29:22]	[Step 1/1]     / ____/___  ____/ /___ ________  __
[11:29:22]	[Step 1/1]    / /   / __ \/ __  / __ `/ ___/ / / /
[11:29:22]	[Step 1/1]   / /___/ /_/ / /_/ / /_/ / /__/ /_/ /
[11:29:22]	[Step 1/1]   \____/\____/\__,_/\__,_/\___/\__, /
[11:29:22]	[Step 1/1]                               /____/
[11:29:22]	[Step 1/1] 
[11:29:22]	[Step 1/1]   Codacy Coverage Reporter
[11:29:22]	[Step 1/1] 
[11:29:22]	[Step 1/1]  --> Using codacy reporter codacy-coverage-reporter-linux from cache
[11:29:23]	[Step 1/1] 2020-05-31 09:29:23.766Z  info [ConfigurationRules] API base URL: https://api.codacy.com  - (ConfigurationRules.scala:84)
[11:29:23]	[Step 1/1] 2020-05-31 09:29:23.767Z  info [ReportRules] Parsing coverage data from: /opt/buildagent/work/5360a1a0b7334b8a/./coverage.xml ...  - (ReportRules.scala:48)
[11:29:23]	[Step 1/1] 2020-05-31 09:29:23.781Z  info [ReportRules] Generated report: /var/tmp/codacy-coverage-17117391641716937672.json (9.43 kB)  - (ReportRules.scala:222)
[11:29:23]	[Step 1/1] 2020-05-31 09:29:23.781Z  info [ReportRules] Uploading coverage data...  - (ReportRules.scala:223)
[11:29:28]	[Step 1/1] Exception in thread "main" java.net.SocketTimeoutException: Read timed out
[11:29:28]	[Step 1/1] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_net_SocketTimeoutException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
[11:29:28]	[Step 1/1] 	at com.oracle.svm.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
[11:29:28]	[Step 1/1] 	at com.oracle.svm.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:801)
[11:29:28]	[Step 1/1] 	at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
[11:29:28]	[Step 1/1] 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
[11:29:28]	[Step 1/1] 	at java.net.SocketInputStream.read(SocketInputStream.java:168)
[11:29:28]	[Step 1/1] 	at java.net.SocketInputStream.read(SocketInputStream.java:140)
[11:29:28]	[Step 1/1] 	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
[11:29:28]	[Step 1/1] 	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
[11:29:28]	[Step 1/1] 	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1103)
[11:29:28]	[Step 1/1] 	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
[11:29:28]	[Step 1/1] 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
[11:29:28]	[Step 1/1] 	at java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
[11:29:28]	[Step 1/1] 	at java.io.BufferedInputStream.read(BufferedInputStream.java:351)
[11:29:28]	[Step 1/1] 	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754)
[11:29:28]	[Step 1/1] 	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
[11:29:28]	[Step 1/1] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1610)
[11:29:28]	[Step 1/1] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
[11:29:28]	[Step 1/1] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[11:29:28]	[Step 1/1] 	at scalaj.http.HttpRequest.doConnection(Http.scala:365)
[11:29:28]	[Step 1/1] 	at scalaj.http.HttpRequest.exec(Http.scala:343)
[11:29:28]	[Step 1/1] 	at scalaj.http.HttpRequest.asString(Http.scala:491)
[11:29:28]	[Step 1/1] 	at com.codacy.api.client.CodacyClient.post(CodacyClient.scala:74)
[11:29:28]	[Step 1/1] 	at com.codacy.api.service.CoverageServices.postRequest(CoverageServices.scala:91)
[11:29:28]	[Step 1/1] 	at com.codacy.api.service.CoverageServices.sendReport(CoverageServices.scala:27)
[11:29:28]	[Step 1/1] 	at com.codacy.rules.ReportRules.sendReport(ReportRules.scala:126)
[11:29:28]	[Step 1/1] 	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$8(ReportRules.scala:54)
[11:29:28]	[Step 1/1] 	at scala.util.Either.flatMap(Either.scala:341)
[11:29:28]	[Step 1/1] 	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$7(ReportRules.scala:53)
[11:29:28]	[Step 1/1] 	at scala.util.Either.flatMap(Either.scala:341)
[11:29:28]	[Step 1/1] 	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$6(ReportRules.scala:52)
[11:29:28]	[Step 1/1] 	at scala.util.Either.flatMap(Either.scala:341)
[11:29:28]	[Step 1/1] 	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$4(ReportRules.scala:51)
[11:29:28]	[Step 1/1] 	at scala.util.Either.flatMap(Either.scala:341)
[11:29:28]	[Step 1/1] 	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$3(ReportRules.scala:50)
[11:29:28]	[Step 1/1] 	at scala.collection.immutable.List.map(List.scala:286)
[11:29:28]	[Step 1/1] 	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$2(ReportRules.scala:47)
[11:29:28]	[Step 1/1] 	at scala.util.Either.flatMap(Either.scala:341)
[11:29:28]	[Step 1/1] 	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$1(ReportRules.scala:40)
[11:29:28]	[Step 1/1] 	at com.codacy.rules.ReportRules.$anonfun$withCommitUUID$4(ReportRules.scala:265)
[11:29:28]	[Step 1/1] 	at com.codacy.rules.ReportRules.$anonfun$withCommitUUID$4$adapted(ReportRules.scala:265)
[11:29:28]	[Step 1/1] 	at scala.util.Either.flatMap(Either.scala:341)
[11:29:28]	[Step 1/1] 	at com.codacy.rules.ReportRules.withCommitUUID(ReportRules.scala:265)
[11:29:28]	[Step 1/1] 	at com.codacy.rules.ReportRules.codacyCoverage(ReportRules.scala:35)
[11:29:28]	[Step 1/1] 	at com.codacy.CodacyCoverageReporter$.$anonfun$sendReport$1(CodacyCoverageReporter.scala:43)
[11:29:28]	[Step 1/1] 	at scala.util.Either.flatMap(Either.scala:341)
[11:29:28]	[Step 1/1] 	at com.codacy.CodacyCoverageReporter$.sendReport(CodacyCoverageReporter.scala:34)
[11:29:28]	[Step 1/1] 	at com.codacy.CodacyCoverageReporter$.run(CodacyCoverageReporter.scala:19)
[11:29:28]	[Step 1/1] 	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:13)
[11:29:28]	[Step 1/1] 	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:11)
[11:29:28]	[Step 1/1] 	at caseapp.CommandAppWithPreCommand.$anonfun$main$1(CommandAppWithPreCommand.scala:97)
[11:29:28]	[Step 1/1] 	at caseapp.CommandAppWithPreCommand.$anonfun$main$1$adapted(CommandAppWithPreCommand.scala:82)
[11:29:28]	[Step 1/1] 	at scala.Option.foreach(Option.scala:407)
[11:29:28]	[Step 1/1] 	at caseapp.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:82)
[11:29:28]	[Step 1/1] 	at com.codacy.CodacyCoverageReporter.main(CodacyCoverageReporter.scala)
[11:29:28]	[Step 1/1] 
[11:29:28]	[Step 1/1]  --> Failed!
```


The last time this worked on our end was on the 29.05.2020

**Comment by Sparrow0hawk** [comment]
I also get this error on a build that ran without issues 5 days ago.

Previous working build log (https://travis-ci.com/github/Sparrow0hawk/topic_model_to_Shiny_app/jobs/340182647).

Current erroring build (https://travis-ci.com/github/Sparrow0hawk/topic_model_to_Shiny_app/jobs/341874964).

Relevant log output:

```{bash}
The command "coverage xml" exited with 0.

7.73s$ bash <(wget -q -O - https://coverage.codacy.com/get.sh) report -l python -r coverage.xml

     ______          __

    / ____/___  ____/ /___ ________  __

   / /   / __ \/ __  / __ `/ ___/ / / /

  / /___/ /_/ / /_/ / /_/ / /__/ /_/ /

  \____/\____/\__,_/\__,_/\___/\__, /

                              /____/

  Codacy Coverage Reporter

 --> Download the codacy reporter codacy-coverage-reporter-linux... (latest)

######################################################################## 100.0%

######################################################################## 100.0%

2020-05-31 09:44:18.359Z  info [ConfigurationRules] API base URL: https://api.codacy.com  - (ConfigurationRules.scala:84)

2020-05-31 09:44:18.360Z  info [ReportRules] Parsing coverage data from: /home/travis/build/Sparrow0hawk/topic_model_to_Shiny_app/coverage.xml ...  - (ReportRules.scala:48)

2020-05-31 09:44:18.371Z  info [ReportRules] Generated report: /var/tmp/codacy-coverage-3435432345807046271.json (3.09 kB)  - (ReportRules.scala:222)

2020-05-31 09:44:18.371Z  info [ReportRules] Uploading coverage data...  - (ReportRules.scala:223)

Exception in thread "main" java.net.SocketTimeoutException: Read timed out

	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_net_SocketTimeoutException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)

	at com.oracle.svm.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)

	at com.oracle.svm.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:801)

	at java.net.SocketInputStream.socketRead0(SocketInputStream.java)

	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115)

	at java.net.SocketInputStream.read(SocketInputStream.java:168)

	at java.net.SocketInputStream.read(SocketInputStream.java:140)

	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)

	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)

	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1103)

	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)

	at java.io.BufferedInputStream.fill(BufferedInputStream.java:252)

	at java.io.BufferedInputStream.read1(BufferedInputStream.java:292)

	at java.io.BufferedInputStream.read(BufferedInputStream.java:351)

	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754)

	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1610)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)

	at scalaj.http.HttpRequest.doConnection(Http.scala:365)

	at scalaj.http.HttpRequest.exec(Http.scala:343)

	at scalaj.http.HttpRequest.asString(Http.scala:491)

	at com.codacy.api.client.CodacyClient.post(CodacyClient.scala:74)

	at com.codacy.api.service.CoverageServices.postRequest(CoverageServices.scala:91)

	at com.codacy.api.service.CoverageServices.sendReport(CoverageServices.scala:27)

	at com.codacy.rules.ReportRules.sendReport(ReportRules.scala:126)

	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$8(ReportRules.scala:54)

	at scala.util.Either.flatMap(Either.scala:341)

	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$7(ReportRules.scala:53)

	at scala.util.Either.flatMap(Either.scala:341)

	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$6(ReportRules.scala:52)

	at scala.util.Either.flatMap(Either.scala:341)

	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$4(ReportRules.scala:51)

	at scala.util.Either.flatMap(Either.scala:341)

	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$3(ReportRules.scala:50)

	at scala.collection.immutable.List.map(List.scala:286)

	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$2(ReportRules.scala:47)

	at scala.util.Either.flatMap(Either.scala:341)

	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$1(ReportRules.scala:40)

	at com.codacy.rules.ReportRules.$anonfun$withCommitUUID$4(ReportRules.scala:265)

	at com.codacy.rules.ReportRules.$anonfun$withCommitUUID$4$adapted(ReportRules.scala:265)

	at scala.util.Either.flatMap(Either.scala:341)

	at com.codacy.rules.ReportRules.withCommitUUID(ReportRules.scala:265)

	at com.codacy.rules.ReportRules.codacyCoverage(ReportRules.scala:35)

	at com.codacy.CodacyCoverageReporter$.$anonfun$sendReport$1(CodacyCoverageReporter.scala:43)

	at scala.util.Either.flatMap(Either.scala:341)

	at com.codacy.CodacyCoverageReporter$.sendReport(CodacyCoverageReporter.scala:34)

	at com.codacy.CodacyCoverageReporter$.run(CodacyCoverageReporter.scala:19)

	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:13)

	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:11)

	at caseapp.CommandAppWithPreCommand.$anonfun$main$1(CommandAppWithPreCommand.scala:97)

	at caseapp.CommandAppWithPreCommand.$anonfun$main$1$adapted(CommandAppWithPreCommand.scala:82)

	at scala.Option.foreach(Option.scala:407)

	at caseapp.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:82)

	at com.codacy.CodacyCoverageReporter.main(CodacyCoverageReporter.scala)

 --> Failed!

The command "bash <(wget -q -O - https://coverage.codacy.com/get.sh) report -l python -r coverage.xml" exited with 1.


```

**Comment by raul-sr** [comment]
i have the same problem with jacoco

![image](https://user-images.githubusercontent.com/66186915/83362447-ee5feb80-a356-11ea-9079-0e52792f485c.png)

**Comment by newbe36524** [comment]
me too.
But in github action:
https://github.com/newbe36524/Newbe.Claptrap/pull/15/checks?check_run_id=726829843

**Comment by franciscodua** [comment]
Hi
We suffered an outage during the weekend that affected the coverage report endpoint. But the problem is fixed and reporting coverage should work as expected from now on.

We apologize for the impact this had on your work.
If you're still experiencing these problems, re-open this issue or create a new one

**Comment by alexesprit** [comment]
Can confirm it's fixed - I ran my failed workflows again, and they are green now. Thanks!
