### ISSUE TITLE
Remove jpm from setup instructions or pressure to fix

### ISSUE THREAD

**Issue by jjohnson** [codacy/codacy-coverage-reporter#28]
```
curl http://www.jpm4j.org/install/script > installjpm.sh
sudo sh installjpm.sh
sudo jpm -te install com.codacy:codacy-coverage-reporter:assembly
```
```
Using settings file: ~/.jpm/settings.json
# default
# home=/var/jpm, bin=/usr/local/bin
# home=/var/jpm, bin=/usr/local/bin
# install com.codacy:codacy-coverage-reporter:assembly
# coordinate com.codacy:codacy-coverage-reporter:assembly
# -> {jsonrpc:"2.0",method:"getRevisionByCoordinate",params:["com.codacy:codacy-coverage-reporter:assembly"],id:1468032023592}
# Sentx 
# Error 
# <- http://repo.jpm4j.org/jsonrpc/2.0/jpm
# ERROR: [URLClient.send] http://repo.jpm4j.org/jsonrpc/2.0/jpm
java.lang.Exception: http://repo.jpm4j.org/jsonrpc/2.0/jpm
	at aQute.rest.urlclient.URLClient.send(URLClient.java:162)
	at aQute.rest.urlclient.URLClient.put(URLClient.java:179)
	at aQute.jsonrpc.proxy.JSONRPCProxy.invokeSync(JSONRPCProxy.java:91)
	at aQute.jsonrpc.proxy.JSONRPCProxy.invoke(JSONRPCProxy.java:63)
	at com.sun.proxy.$Proxy5.getRevisionByCoordinate(Unknown Source)
	at aQute.jpm.lib.JustAnotherPackageManager.getCandidateAsync(JustAnotherPackageManager.java:942)
	at aQute.jpm.lib.JustAnotherPackageManager.getCandidate(JustAnotherPackageManager.java:903)
	at aQute.jpm.main.Main._install(Main.java:472)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at aQute.lib.getopt.CommandLine.execute(CommandLine.java:149)
	at aQute.jpm.main.Main._jpm(Main.java:366)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at aQute.lib.getopt.CommandLine.execute(CommandLine.java:149)
	at aQute.jpm.main.Main.run(Main.java:797)
	at aQute.jpm.main.Main.main(Main.java:118)
Caused by: java.lang.Exception: Failed request 405:HTTP method PUT is not supported by this URL <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 405 </title>
</head>
<body>
<h2>HTTP ERROR: 405</h2>
<p>Problem accessing /jsonrpc/2.0/jpm. Reason:
<pre>    HTTP method PUT is not supported by this URL</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
	at aQute.rest.urlclient.URLClient.send(URLClient.java:130)
	... 20 more
Error
  0. [URLClient.send] http://repo.jpm4j.org/jsonrpc/2.0/jpm
```

You could also just navigate to http://jpm4j.org/ or http://repo.jpm4j.org and see the 405

Also doubt your other product will build if you commit there, https://github.com/codacy/codacy-api-java/blob/fix/docs/circle.yml

**Comment by pedrorijo91** [comment]
Hey @jjohnson 

Sorry for taking some time to answer to your issue.

Is it still happening? We have some internal projects that are using this plugin and they didn't report any problem as far as I know. It seems more a rare problem that affected JPM servers

**Comment by halkeye** [comment]
as of early august, the https certificates are expired.

Can this be distributed another way?

**Comment by pedrorijo91** [comment]
Hey @halkeye,

Have you tried to [build from source](https://github.com/codacy/codacy-coverage-reporter#build-from-source) ?

**Comment by halkeye** [comment]
not yet, i'm still trying to figure out how I want to do all this from a CI platform, so just poking around at options for now.

As with #22, I might look into learning how to make maven plugins.

**Comment by pedrorijo91** [comment]
if you decide to go for a maven plugin, let us know. We will gladly help you in everything we can @halkeye :)

**Comment by pedrorijo91** [comment]
closing as duplicated from #22
