### ISSUE TITLE
[CY-4663] Failure to report when executing in JAVA16

### ISSUE THREAD

**Issue by brajjan79** [codacy/codacy-coverage-reporter#329]
### Are you looking for help?

No, I am not looking for help, just reporting an incompatability problem with JAVA 16.

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

* Linux / travis in Github
* Git bash on windows

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Should report coverage

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

When trying to parse jacoco report throws "java.lang.IllegalAccessError:" exception.

### Reproducible Test Case

1. Produce jacoco report:
   a) mvn clean test jacoco:report
2. Download reporting tool:
  b) curl -Ls -o codacy-coverage-reporter-assembly.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/12.2.0/codacy-coverage-reporter-assembly.jar
3. Execute reporting tool:
  c) java -jar codacy-coverage-reporter-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml

### Stack Traces

Produces 2 different stack traces depending on where I execute the command.

#### Travis:
Exception in thread "main" java.lang.IllegalAccessError: class com.codacy.parsers.util.XMLoader$ (in unnamed module @0x5fb2de77) cannot access class com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.jaxp to unnamed module @0x5fb2de77
	at com.codacy.parsers.util.XMLoader$.parser(XMLoader.scala:9)
	at scala.xml.factory.XMLLoader$class.loadFile(XMLLoader.scala:48)
	at com.codacy.parsers.util.XMLoader$.loadFile(XMLoader.scala:6)
	at com.codacy.parsers.implementation.CoberturaParser$$anonfun$1.apply(CoberturaParser.scala:17)
	at com.codacy.parsers.implementation.CoberturaParser$$anonfun$1.apply(CoberturaParser.scala:17)
	at scala.util.Try$.apply(Try.scala:192)
	at com.codacy.parsers.implementation.CoberturaParser$.parse(CoberturaParser.scala:17)
	at com.codacy.parsers.CoverageParser$$anonfun$parse$1.apply(CoverageParser.scala:30)
	at com.codacy.parsers.CoverageParser$$anonfun$parse$1.apply(CoverageParser.scala:30)
	at scala.collection.immutable.Stream.map(Stream.scala:418)
	at com.codacy.parsers.CoverageParser$.parse(CoverageParser.scala:30)
	at com.codacy.rules.ReportRules$$anonfun$coverageWithTokenAndCommit$1.apply(ReportRules.scala:45)
	at com.codacy.rules.ReportRules$$anonfun$coverageWithTokenAndCommit$1.apply(ReportRules.scala:40)
	at cats.syntax.EitherOps$.flatMap$extension(either.scala:148)
	at com.codacy.rules.ReportRules.withCommitUUID(ReportRules.scala:124)
	at com.codacy.rules.ReportRules.coverageWithTokenAndCommit(ReportRules.scala:40)
	at com.codacy.rules.ReportRules.codacyCoverage(ReportRules.scala:30)
	at com.codacy.CodacyCoverageReporter$.run(CodacyCoverageReporter.scala:22)
	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:13)
	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:11)
	at caseapp.CommandAppWithPreCommand$$anonfun$main$1.apply(CommandAppWithPreCommand.scala:97)
	at caseapp.CommandAppWithPreCommand$$anonfun$main$1.apply(CommandAppWithPreCommand.scala:82)
	at scala.Option.foreach(Option.scala:257)
	at caseapp.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:82)
	at com.codacy.CodacyCoverageReporter.main(CodacyCoverageReporter.scala)

#### Git Bash:
Exception in thread "main" java.lang.IllegalAccessError: class com.codacy.parsers.util.XMLoader$ (in unnamed module @0x10feca44) cannot access class com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.jaxp to unnamed module @0x10feca44
        at com.codacy.parsers.util.XMLoader$.parser(XMLoader.scala:9)
        at scala.xml.factory.XMLLoader.loadFile(XMLLoader.scala:48)
        at scala.xml.factory.XMLLoader.loadFile$(XMLLoader.scala:48)
        at com.codacy.parsers.util.XMLoader$.loadFile(XMLoader.scala:6)
        at com.codacy.parsers.XmlReportParser.$anonfun$loadXmlReport$1(XmlReportParser.scala:17)
        at scala.util.Try$.apply(Try.scala:213)
        at com.codacy.parsers.XmlReportParser.loadXmlReport(XmlReportParser.scala:17)
        at com.codacy.parsers.XmlReportParser.loadXmlReport$(XmlReportParser.scala:16)
        at com.codacy.parsers.implementation.CoberturaParser$.loadXmlReport(CoberturaParser.scala:12)
        at com.codacy.parsers.XmlReportParser.parseReport(XmlReportParser.scala:35)
        at com.codacy.parsers.XmlReportParser.parseReport$(XmlReportParser.scala:32)
        at com.codacy.parsers.implementation.CoberturaParser$.parseReport(CoberturaParser.scala:12)
        at com.codacy.parsers.implementation.CoberturaParser$.parse(CoberturaParser.scala:20)
        at com.codacy.parsers.CoverageParser$ParsedCoverage$1$.unapply(CoverageParser.scala:53)
        at com.codacy.parsers.CoverageParser$$anonfun$parse$4.applyOrElse(CoverageParser.scala:62)
        at com.codacy.parsers.CoverageParser$$anonfun$parse$4.applyOrElse(CoverageParser.scala:61)
        at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:172)
        at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:159)
        at scala.collection.SeqLike$$anon$2.collectFirst(SeqLike.scala:682)
        at com.codacy.parsers.CoverageParser$.parse(CoverageParser.scala:61)
        at com.codacy.rules.ReportRules.$anonfun$sendFilesReportForCommit$2(ReportRules.scala:46)
        at scala.util.Either.flatMap(Either.scala:341)
        at com.codacy.rules.ReportRules.$anonfun$sendFilesReportForCommit$1(ReportRules.scala:45)
        at scala.collection.immutable.List.map(List.scala:286)
        at com.codacy.rules.ReportRules.sendFilesReportForCommit(ReportRules.scala:42)
        at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$2(ReportRules.scala:78)
        at scala.util.Either.flatMap(Either.scala:341)
        at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$1(ReportRules.scala:70)
        at com.codacy.rules.ReportRules.$anonfun$withCommitUUID$4(ReportRules.scala:307)
        at scala.util.Either.flatMap(Either.scala:341)
        at com.codacy.rules.ReportRules.withCommitUUID(ReportRules.scala:307)
        at com.codacy.rules.ReportRules.codacyCoverage(ReportRules.scala:65)
        at com.codacy.CodacyCoverageReporter$.$anonfun$sendReport$1(CodacyCoverageReporter.scala:43)
        at scala.util.Either.flatMap(Either.scala:341)
        at com.codacy.CodacyCoverageReporter$.sendReport(CodacyCoverageReporter.scala:34)
        at com.codacy.CodacyCoverageReporter$.run(CodacyCoverageReporter.scala:19)
        at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:15)
        at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:13)
        at caseapp.CommandAppWithPreCommand.$anonfun$main$1(CommandAppWithPreCommand.scala:97)
        at caseapp.CommandAppWithPreCommand.$anonfun$main$1$adapted(CommandAppWithPreCommand.scala:82)
        at scala.Option.foreach(Option.scala:407)
        at caseapp.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:82)
        at com.codacy.CodacyCoverageReporter.main(CodacyCoverageReporter.scala)

**Comment by machadoit** [comment]
Hi @brajjan79 our java binary is intended to work for Java 8, opened a PR to clarify it, as we don't have plans on supporting it for newer versions.

Is it possible for you to use the main script to send coverage instead of using the jar? As instructed at https://docs.codacy.com/coverage-reporter/#uploading-coverage ?
