### ISSUE TITLE
Unable to upload report due to conversion error from XML report to JSON

### ISSUE THREAD

**Issue by davidgoate** [codacy/codacy-coverage-reporter#66]
### Scala Version (2.10.x / etc)
None

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.12.6

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

1.8.0_72, vendor: Oracle Corporation

### Expected Behavior

mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=myProjectToken -DapiToken=myApiToken

Should upload my codacy report

### Actual Behavior

```
Failed to execute goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage (default-cli) on project service-discovery-server: Execution default-cli of goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage failed: null -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage (default-cli) on project service-discovery-server: Execution default-cli of goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage failed: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage failed: null
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: scala.MatchError: null
	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:253)
	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:251)
	at scala.PartialFunction$Unlifted.applyOrElse(PartialFunction.scala:233)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at play.api.libs.functional.FunctionalBuilder$CanBuild3$$anonfun$apply$8.apply(Products.scala:76)
	at play.api.libs.functional.FunctionalBuilder$CanBuild3$$anonfun$apply$8.apply(Products.scala:76)
	at play.api.libs.json.OFormat$$anon$5$$anonfun$inmap$2.apply(Format.scala:32)
	at play.api.libs.json.OFormat$$anon$5$$anonfun$inmap$2.apply(Format.scala:32)
	at play.api.libs.json.OFormat$$anon$1.writes(Format.scala:42)
	at play.api.libs.json.OFormat$$anon$1.writes(Format.scala:38)
	at play.api.libs.json.Json$.toJson(Json.scala:108)
	at play.api.libs.json.Json.toJson(Json.scala)
	at com.gavinmogan.CodacyCoverageReporterMojo.postReport(CodacyCoverageReporterMojo.java:147)
	at com.gavinmogan.CodacyCoverageReporterMojo.execute(CodacyCoverageReporterMojo.java:130)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more

```

**Comment by davidgoate** [comment]
Some searching suggests perhaps this can occur when using `null` instead of `None` in the type that is being converted.

**Comment by rtfpessoa** [comment]
Hi @davidgoate since you are using the plugin built by @halkeye you need to check with him here https://github.com/halkeye/codacy-maven-plugin. Let me know if I can help with anything.

Closing for now. If you need any help from us I will re-open.

**Comment by davidgoate** [comment]
@rtfpessoa thanks for this. Would be awesome if Codacy could one day plan to add an official Maven plugin to their offering!

**Comment by rtfpessoa** [comment]
@davidgoate I will forward this request to product 👍
